### ISSUE TITLE
Multiple books allowed

### ISSUE THREAD

**Issue by SlimeDog** [FlailoftheLord/FishyLecterns#1]
Spigot 1.14.4 (Jenkins 2423)
FishyLecterns 1.0

Despite
```
CanHaveMultipleBooks: false
```
player was able to take multiple books from the fishy lectern. Player was op'd and in creative gamemode, but neither of those should make a difference.

**Comment by FlailoftheLord** [comment]
You'll have to remove the permission `fishylecterns.bypass`  It allows any player (default for op) to bypass any limits.

**Comment by SlimeDog** [comment]
Thanks. Verified expected result when
>fishylecterns.bypass: false

Please note on Overview that all permissions default to _true_ for OP.
