### ISSUE TITLE
Duplicate fishy lecterns.yml

### ISSUE THREAD

**Issue by SlimeDog** [FlailoftheLord/FishyLecterns#4]
Spigot 1.14.4 (Jenkins 2492)
FishyLecterns 1.0

There is only one FishyLectern on my server, located in world_lobby. But identical (and redundant) content has been created in multiple _world*/fishylecterns.yml_ files, all of them describing the location of the world_lobby FishyLectern.

**Comment by FlailoftheLord** [comment]
Yikes, I'll fix that up, also going to change the datafile storage

**Comment by SlimeDog** [comment]
Spigot 1.14.4
FishyLecterns 1.1

On server start-up, the following were created:
- world/fishylecterns.yml
- world_nether/fishylecterns.yml
- world_the_end/fishylecterns.yml

All contain:
> LecternLocations: !!set {}

Also, see #6.
