### ISSUE TITLE
Placement of fishylecterns.yml

### ISSUE THREAD

**Issue by SlimeDog** [FlailoftheLord/FishyLecterns#6]
IMHO (see #2), fishylecterns.yml should not be created in the world subdirectories. It should be created in the plugins/FishyLecterns/ subdirectory. That is
> plugins/FishyLecterns/fishylecterns.yml

If you like, it could contains per world sections. That is not necessary, since the world is identified. For example:
```
LecternLocations: !!set
  ? ==: org.bukkit.Location
    world: world_lobby
    x: 0.0
    y: 34.0
    z: -5.0
    pitch: 0.0
    yaw: 0.0
  : null
```
Not sure why pitch and yaw are needed. Since lecterns have neither.

**Comment by FlailoftheLord** [comment]
I wanted to keep the data in the world's data folder so when changing worlds you dont have random blocks specified as "lecterns" also letting the plugin quickly scan any world folder and find all the special lecterns.  The files are generated in each world folder with an empty set if no lecterns are created in that world, as that's how the library i made for DataFiles works

If you insist though, I can change it, I just prefer for all block data to be stored directly in the world folder.

The way they are stored is just a Set of the blocks' Location object. Its faster to store it directly than store each coordinate individually.

**Comment by FlailoftheLord** [comment]
Added config toggle.
https://github.com/FlailoftheLord/FishyLecterns/commit/9b23e017ab86d3b69ba616b27cc93795bb746e10

**Comment by SlimeDog** [comment]
Spigot 1.14.4
FishyLecterns 1.2

> The way they are stored is just a Set of the blocks' Location object. Its faster to store it directly than store each coordinate individually.

I can understand why speed would be the major consideration here. So much data, so little time. You could save some time by not creating files that have no data.

On world start-up, empty files are created in the world subdirectories, even though the configuration says to store them in the new location, and the worlds have no lecterns (first data point is file length):
```
   0 Oct 30 07:37 UNIVERSE/world/fishylecterns.yml
   0 Oct 30 07:37 UNIVERSE/world_nether/fishylecterns.yml
   0 Oct 30 07:37 UNIVERSE/world_the_end/fishylecterns.yml
```
Files are also created in the new locations, with no substantive data:
```
  27 Oct 30 07:37 plugins/FishyLecterns/data/world/fishylecterns.yml
  27 Oct 30 07:37 plugins/FishyLecterns/data/world_nether/fishylecterns.yml
  27 Oct 30 07:37 plugins/FishyLecterns/data/world_the_end/fishylecterns.yml
```
When I place a lectern, files are created in both locations; the empty file in the worlds subdirectory, and the substantive file in the new location:
```
   0 Oct 30 07:41 UNIVERSE/world_lobby/fishylecterns.yml
 147 Oct 30 07:43 plugins/FishyLecterns/data/world_lobby/fishylecterns.yml
```

**Comment by SlimeDog** [comment]
The three files in the worlds subdirectory are created at server start-up, even if they had been removed explicitly previously.
```
   0 Oct 30 08:08 UNIVERSE/world/fishylecterns.yml
   0 Oct 30 08:08 UNIVERSE/world_nether/fishylecterns.yml
   0 Oct 30 08:08 UNIVERSE/world_the_end/fishylecterns.yml
```

**Comment by SlimeDog** [comment]
Closed due to dev disinterest.
